---
  - name: My first playbook
    hosts: webservers
    become: true
    tasks:

    - name: Update cache
      apt:
       update_cache: yes

    - name: Install docker.io
      apt:
        name: docker.io
        state: present

    - name: Install python3
      apt:
        name: python3-pip
        state: present

    - name: install docker python package
      pip:
        name: docker

    - name: create a container
      docker_container:
        name: dvwa_container
        image: cyberxsecurity/dvwa
        state: started
        published_ports: 80:80
        restart_policy: always

    - name: Make sure docker service is started
      systemd:
        enabled: yes
        name: docker

