---
  - name: Playbook to install and configure filebeat
    hosts: webservers
    become: true
    tasks:

    - name: Download the filebeat installation file
      command:
       cmd: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb
       creates: filebeat-7.4.0-amd64.deb

    - name: Install Filebeat
      command: sudo dpkg -i filebeat-7.4.0-amd64.deb

    - name: Copy the filebeat config file to the ElkVM
      copy:
        src: /etc/ansible/roles/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Enable Filebeat modules
      command: filebeat modules enable system

    - name: Filebeat set up
      command: filebeat setup

    - name: Start Filebeat
      command: service filebeat start

    - name: Enable Filebeat service on boot
      systemd:
        name: filebeat
        enabled: yes

