---
  - name: Playbook to install and configure Metricbeat
    hosts: webservers
    become: true
    tasks:

    - name: Download and install metricbeat
      apt:
       deb: "https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb"
       state: present

    - name: Enable Metricbeat modules
      command: metricbeat modules enable docker

    - name: Metricbeat set up
      command: metricbeat setup

    - name: Start metricbeat
      command: service metricbeat start

    - name: Enable Metricbeat service on boot
      systemd:
        name: metricbeat
        enabled: yes

